# Generated by Django 3.2.2 on 2021-05-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='lead_gen',
            new_name='created_on',
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_name',
            field=models.CharField(blank=True, default='/', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(choices=[('N', 'New'), ('C', 'Cold'), ('W', 'Warm'), ('H', 'Hot'), ('I', 'Hot Ice')], default='N', max_length=1),
        ),
    ]
